server:
  port: 8088

spring:
  application:
   name: gateway-service
  cloud:
    gateway:
      routes:
        - id: eureka-route
          uri: lb://eureka-service
          predicates:
            - Path=/eureka/**
          filters:
            - StripPrefix=1

      discovery:
        locator:
          enabled: true
          lower-case-service-id: true



eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8090/eureka/


