# \u5E94\u7528\u540D\u79F0
spring:
  application:
   name: eureka-service
# \u5E94\u7528\u670D\u52A1 WEB \u8BBF\u95EE\u7AEF\u53E3
server:
  port: 8090


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8090/eureka/